### ISSUE TITLE
Cannot install, duplicate function declaration

### ISSUE THREAD

**Issue by brenjt** [laravel/boost#67]
### Laravel Package Version

1.0.3

### Laravel Version

12.20.0

### PHP Version

8.3.15

### Description

When running `php artisan boost:install` I get duplicate declaration of helper functions that are loading via composer

```
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
```

Cannot redeclare template_path() (previously declared in html/app/helpers.php:6)

### Steps To Reproduce

`composer require laravel/boost --dev`

Add helpers file to autoloader and place function inside.

run `php artisan boost:install`
Select PHPStorm, then Junie

**Comment by negoziator** [comment]
I think you can just add 

```php
if (! function_exists(`your-function` )
```

in front of all your functions in `helpers.php`

**Comment by inxilpro** [comment]
We bumped into this as well. The `function_exists` check is OK, but ideally boost wouldn't be triggering a double-call to the autoloaded files in the first place.

**Comment by ashleyhindle** [comment]
This isn't something we're _actively_ doing, and annoyingly hasn't happened in any testing so far 😬 

I'll somehow make this happen tomorrow to find a fix, it seems very peculiar!

**Comment by modernben** [comment]
Happening on my project as well
Composer for reference

```json
 "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Database\\Queries\\": "database/queries/",
            "Database\\Queries\\Views\\": "database/queries/views/"
        },
        "files": [
            "app/Support/helpers.php"
        ]
    },
```

**Comment by zdearo** [comment]
Going through the same situation here.

```json
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/functions-helpers.php"
        ]
    },
```

**Comment by karakhanyans** [comment]
Happens to me too

if (! function_exists(`your-function` ) helped as a quick solution

**Comment by sarfraznawaz2005** [comment]
Exactly what was happening with me in #51 , ended up using `! function_exists`

**Comment by ashleyhindle** [comment]
@zdearo fixed this with https://github.com/laravel/boost/pull/99 - please run `composer update` and re-test 🙌

**Comment by michaelsieminski** [comment]
> [@zdearo](https://github.com/zdearo) fixed this with [#99](https://github.com/laravel/boost/pull/99) - please run `composer update` and re-test 🙌

I still experience this issue with v1.0.12. Getting cannot redeclare errors for the functions in my helpers.php when trying to do boost install

**Comment by ashleyhindle** [comment]
> > [@zdearo](https://github.com/zdearo) fixed this with [#99](https://github.com/laravel/boost/pull/99) - please run `composer update` and re-test 🙌
> 
> I still experience this issue with v1.0.12. Getting cannot redeclare errors for the functions in my helpers.php when trying to do boost install

Ah I wonder if your helper file contains class keywords like interface/class/trait/etc.. 🤔 hmmm

**Comment by krisimmig** [comment]
> > > [@zdearo](https://github.com/zdearo) fixed this with [#99](https://github.com/laravel/boost/pull/99) - please run `composer update` and re-test 🙌
> > 
> > 
> > I still experience this issue with v1.0.12. Getting cannot redeclare errors for the functions in my helpers.php when trying to do boost install
> 
> Ah I wonder if your helper file contains class keywords like interface/class/trait/etc.. 🤔 hmmm

That is indeed the case, in our project we have the same install error and the helper file does include "class", .e.g. `$generator = app(\Illuminate\Routing\UrlGenerator::class);`.

**Comment by ciungulete** [comment]
I still experience this issue with:
`Cannot redeclare class Domain\Support\Actions\Action (previously declared in /app/Domain/Support/Actions/Action.php:)`

**Comment by krisimmig** [comment]
**Quickfix**: temporary remove all code form helper.php, run install script and then add back the code to helper.php; 
I think the script is not supposed to do anything with that file anyway.

**Comment by ashleyhindle** [comment]
I've just pushed a new release that should fix this. Please `composer update` and give it a try if you could 🙏

**Comment by ashleyhindle** [comment]
I'm not sure this will fix your issue @ciungulete, but it should fix others.

Is your `Domain\Support\Actions\Action` class autoloaded in `composer.json` under `autoload.files`?

**Comment by ciungulete** [comment]
@ashleyhindle I’m still experiencing the same issue. These classes are located in the Domain folder, and my composer.json autoload section looks like this:
```json
"autoload": {
    "psr-4": {
        "App\\": "app/",
        "Domain\\": "app/Domain/",
        "Database\\Factories\\": "database/factories/",
        "Database\\Seeders\\": "database/seeders/"
    }
}
```
